development:
  adapter: postgresql
  #username: <%= ENV['DATABASE_USER_NAME'] %>
  username: pole_emploi
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: localhost
  database: pole_emploi

test:
  adapter: postgresql
  #username: <%= ENV['DATABASE_USER_NAME'] %>
  username: pole_emploi
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: localhost
  database: pole_emploi_test

#config for dokku / digital ocean
production:
  url: <%= ENV['DATABASE_URL'] %>
  username: <%= ENV['DATABASE_USER_NAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  database: <%= ENV['DATABASE_NAME'] %>
