development:
  adapter: postgresql
  username: <%= ENV['DATABASE_USER_NAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: localhost
  database: pole_emploi

test:
  adapter: postgresql
  username: <%= ENV['DATABASE_USER_NAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: localhost
  database: pole_emploi_test

production:
  url: <%= ENV['DATABASE_URL'] %>
